#
# Vivado (TM) v2016.2 (64-bit)
#
# fpga_fc7_daq_firmware_create_vivado_project.tcl: Tcl script for re-creating project 'fpga_fc7_daq_firmware'
#
# Generated by Vivado on Tue Nov 08 15:29:09 CET 2016
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (fpga_fc7_daq_firmware_create_vivado_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_gt.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_tx_startup_fsm.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_rx_startup_fsm.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_recclk_monitor.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_sync_block.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_reset_sync.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_init.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_trans_decl.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_package.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/usr/user_package_basic.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/sys/system_package.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gig_eth_pcs_pma_v11_4/gig_eth_pcs_pma_v11_4_transceiver.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/icap/icap_package.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_tx_mux.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_txtransactor_if_simple.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_status_buffer.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxtransactor_if_simple.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_shim.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_mux.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rarp_block.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_packet_parser.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_ipaddr_block.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_tx.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_rx.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_do_rx_reset.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_clock_crossing_if.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_byte_sum.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_status.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_resend.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_ping.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_payload.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_arp.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_buffer_selector.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_sm.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_if.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_cfg.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/example_designs/hdl/clock_div.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/usr/user_addr_decode.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/sys/system_version_package.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/uc_spi_interface.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/uc_pipe_interface.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/trans_buffer.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_block.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipbus_addr_decode.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/hdl/emac_hostbus_decl.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/icap/icap_interface_ioControl.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/icap/icap_interface_fsm.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/icap/icap_interface.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/i2c/i2c_ctrl.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/i2c/i2c_bitwise.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_if_flat.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/trans_arb.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/stretcher.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/usr/user_version_package_basic.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/regs/system_regs.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/uc_if.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ip_mac_select.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipbus_sys_fabric.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/hdl/eth_7s_1000basex.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/clocks_7s_serdes_fc7.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/icap/icap_interface_wrapper.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/i2c/i2c_master_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/cdce/spi/spi_master.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_ctrl.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/sys/system_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/sys/fc7_top.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/sdpram_32x9_16x10.ngc"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4.ngc"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/tri_mode_eth_mac_v5_5.ngc"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/sdpram_16x10_32x9.ngc"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/syspll.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/i2c/i2c_eep_autoread.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/i2c/i2c_master_top.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/usr/user_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/hybrid/hybrid_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/fast_command/fast_command_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/command_processor/command_processor_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/clock_generator/clock_generator_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/phy/phy_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/be_data_buffer/be_data_buffer_core.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/sys/ucf/sys.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/ucf/usr_clk.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/FC7-Firmware/fw/src/usr/ucf/user_io.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "fpga_fc7_daq_firmware_create_vivado_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/fpga_fc7_daq_firmware"]"

# Create project
create_project -force fpga_fc7_daq_firmware ./fpga_fc7_daq_firmware -part xc7k420tffg1156-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects fpga_fc7_daq_firmware]
set_property "board_part" "" $obj
set_property "compxlib.activehdl_compiled_library_dir" "$proj_dir/fpga_fc7_daq_firmware.cache/compile_simlib/activehdl" $obj
set_property "compxlib.funcsim" "1" $obj
set_property "compxlib.ies_compiled_library_dir" "$proj_dir/fpga_fc7_daq_firmware.cache/compile_simlib/ies" $obj
set_property "compxlib.modelsim_compiled_library_dir" "$proj_dir/fpga_fc7_daq_firmware.cache/compile_simlib/modelsim" $obj
set_property "compxlib.overwrite_libs" "0" $obj
set_property "compxlib.questa_compiled_library_dir" "$proj_dir/fpga_fc7_daq_firmware.cache/compile_simlib/questa" $obj
set_property "compxlib.riviera_compiled_library_dir" "$proj_dir/fpga_fc7_daq_firmware.cache/compile_simlib/riviera" $obj
set_property "compxlib.timesim" "1" $obj
set_property "compxlib.vcs_compiled_library_dir" "$proj_dir/fpga_fc7_daq_firmware.cache/compile_simlib/vcs" $obj
set_property "compxlib.xsim_compiled_library_dir" "" $obj
set_property "corecontainer.enable" "0" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "enable_optional_runs_sta" "0" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "ip_cache_permissions" "" $obj
set_property "ip_output_repo" "" $obj
set_property "managed_ip" "0" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "pr_flow" "0" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "sim.use_ip_compiled_libs" "0" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj
set_property "target_language" "VHDL" $obj
set_property "target_simulator" "ModelSim" $obj
set_property "xpm_libraries" "" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_gt.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_tx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_rx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_recclk_monitor.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_sync_block.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_reset_sync.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_init.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_trans_decl.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_package.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_package_basic.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/system_package.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gig_eth_pcs_pma_v11_4/gig_eth_pcs_pma_v11_4_transceiver.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_package.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_tx_mux.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_txtransactor_if_simple.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_status_buffer.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxtransactor_if_simple.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_shim.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_mux.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rarp_block.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_packet_parser.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_ipaddr_block.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_tx.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_rx.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_do_rx_reset.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_clock_crossing_if.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_byte_sum.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_status.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_resend.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_ping.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_payload.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_arp.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_buffer_selector.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_sm.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_if.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_cfg.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/example_designs/hdl/clock_div.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_addr_decode.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/system_version_package.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/uc_spi_interface.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/uc_pipe_interface.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/trans_buffer.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_block.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipbus_addr_decode.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/emac_hostbus_decl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface_ioControl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_bitwise.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_if_flat.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/trans_arb.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/stretcher.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_version_package_basic.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/regs/system_regs.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/uc_if.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ip_mac_select.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipbus_sys_fabric.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/eth_7s_1000basex.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/clocks_7s_serdes_fc7.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_master_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/cdce/spi/spi_master.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/system_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/fc7_top.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_32x9_16x10.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/tri_mode_eth_mac_v5_5.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_16x10_32x9.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/syspll.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_eep_autoread.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_master_top.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/hybrid/hybrid_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/fast_command/fast_command_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/command_processor/command_processor_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/clock_generator/clock_generator_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/phy/phy_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_data_buffer/be_data_buffer_core.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_gt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_tx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_rx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_recclk_monitor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_sync_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_reset_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_init.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_trans_decl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/usr/user_package_basic.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/sys/system_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gig_eth_pcs_pma_v11_4/gig_eth_pcs_pma_v11_4_transceiver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_tx_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_txtransactor_if_simple.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_status_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxtransactor_if_simple.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_shim.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rarp_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_packet_parser.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_ipaddr_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_rx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_do_rx_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_clock_crossing_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_byte_sum.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_status.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_resend.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_ping.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_payload.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_arp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_buffer_selector.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_sm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_cfg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/example_designs/hdl/clock_div.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/usr/user_addr_decode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/sys/system_version_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/uc_spi_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/uc_pipe_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/trans_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipbus_addr_decode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/emac_hostbus_decl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface_ioControl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_bitwise.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_if_flat.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/trans_arb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/stretcher.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/usr/user_version_package_basic.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/regs/system_regs.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/uc_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ip_mac_select.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipbus_sys_fabric.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/eth_7s_1000basex.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/clocks_7s_serdes_fc7.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_master_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/cdce/spi/spi_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/sys/system_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/sys/fc7_top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_32x9_16x10.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/tri_mode_eth_mac_v5_5.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_16x10_32x9.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/syspll.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_eep_autoread.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_master_top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/usr/user_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/hybrid/hybrid_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/fast_command/fast_command_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/command_processor/command_processor_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/clock_generator/clock_generator_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/phy/phy_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "$origin_dir/../../src/usr/be_data_buffer/be_data_buffer_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "design_mode" "RTL" $obj
set_property "edif_extra_search_paths" "" $obj
set_property "elab_link_dcps" "1" $obj
set_property "elab_load_timing_constraints" "1" $obj
set_property "generic" "" $obj
set_property "include_dirs" "" $obj
set_property "lib_map_file" "" $obj
set_property "loop_count" "1000" $obj
set_property "name" "sources_1" $obj
set_property "top" "fc7_top" $obj
set_property "verilog_define" "" $obj
set_property "verilog_uppercase" "0" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/sys/ucf/sys.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/sys/ucf/sys.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "processing_order" "NORMAL" $file_obj
set_property "scoped_to_cells" "" $file_obj
set_property "scoped_to_ref" "" $file_obj
set_property "used_in" "implementation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_synthesis" "0" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/usr_clk.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/usr_clk.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "processing_order" "NORMAL" $file_obj
set_property "scoped_to_cells" "" $file_obj
set_property "scoped_to_ref" "" $file_obj
set_property "used_in" "implementation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_synthesis" "0" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/user_io.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/user_io.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "processing_order" "NORMAL" $file_obj
set_property "scoped_to_cells" "" $file_obj
set_property "scoped_to_ref" "" $file_obj
set_property "used_in" "implementation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_synthesis" "0" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "name" "constrs_1" $obj
set_property "target_constrs_file" "[file normalize "$origin_dir/../../src/sys/ucf/sys.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "generic" "" $obj
set_property "include_dirs" "" $obj
set_property "modelsim.64bit" "" $obj
set_property "modelsim.compile.incremental" "1" $obj
set_property "modelsim.compile.load_glbl" "1" $obj
set_property "modelsim.compile.use_explicit_decl" "1" $obj
set_property "modelsim.compile.vcom.more_options" "" $obj
set_property "modelsim.compile.vhdl_syntax" "93" $obj
set_property "modelsim.compile.vlog.more_options" "" $obj
set_property "modelsim.custom_do" "" $obj
set_property "modelsim.custom_udo" "" $obj
set_property "modelsim.elaborate.acc" "1" $obj
set_property "modelsim.elaborate.vopt.more_options" "" $obj
set_property "modelsim.incremental" "1" $obj
set_property "modelsim.log_all_signals" "0" $obj
set_property "modelsim.saif" "" $obj
set_property "modelsim.sdf_delay" "sdfmax" $obj
set_property "modelsim.simulate.custom_do" "" $obj
set_property "modelsim.simulate.custom_udo" "" $obj
set_property "modelsim.simulate.log_all_signals" "0" $obj
set_property "modelsim.simulate.runtime" "1000ns" $obj
set_property "modelsim.simulate.saif" "" $obj
set_property "modelsim.simulate.sdf_delay" "sdfmax" $obj
set_property "modelsim.simulate.uut" "" $obj
set_property "modelsim.simulate.vsim.more_options" "" $obj
set_property "modelsim.unifast" "" $obj
set_property "modelsim.use_explicit_decl" "1" $obj
set_property "modelsim.vcom_more_options" "" $obj
set_property "modelsim.vhdl_syntax" "93" $obj
set_property "modelsim.vlog_more_options" "" $obj
set_property "modelsim.vsim_more_options" "" $obj
set_property "name" "sim_1" $obj
set_property "nl.cell" "" $obj
set_property "nl.incl_unisim_models" "0" $obj
set_property "nl.process_corner" "slow" $obj
set_property "nl.rename_top" "" $obj
set_property "nl.sdf_anno" "1" $obj
set_property "nl.write_all_overrides" "0" $obj
set_property "runtime" "1000ns" $obj
set_property "source_set" "sources_1" $obj
set_property "top" "" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "unit_under_test" "" $obj
set_property "verilog_define" "" $obj
set_property "verilog_uppercase" "0" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k420tffg1156-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "constrset" "constrs_1" $obj
set_property "description" "Vivado Synthesis Defaults" $obj
set_property "flow" "Vivado Synthesis 2014" $obj
set_property "name" "synth_1" $obj
set_property "needs_refresh" "0" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "pr_configuration" "" $obj
set_property "srcset" "sources_1" $obj
set_property "strategy" "Vivado Synthesis Defaults" $obj
set_property "incremental_checkpoint" "" $obj
set_property "include_in_archive" "1" $obj
set_property "steps.synth_design.tcl.pre" "" $obj
set_property "steps.synth_design.tcl.post" "" $obj
set_property "steps.synth_design.args.flatten_hierarchy" "rebuilt" $obj
set_property "steps.synth_design.args.gated_clock_conversion" "off" $obj
set_property "steps.synth_design.args.bufg" "12" $obj
set_property "steps.synth_design.args.fanout_limit" "10000" $obj
set_property "steps.synth_design.args.directive" "Default" $obj
set_property "steps.synth_design.args.retiming" "0" $obj
set_property "steps.synth_design.args.fsm_extraction" "auto" $obj
set_property "steps.synth_design.args.keep_equivalent_registers" "0" $obj
set_property "steps.synth_design.args.resource_sharing" "auto" $obj
set_property "steps.synth_design.args.control_set_opt_threshold" "auto" $obj
set_property "steps.synth_design.args.no_lc" "0" $obj
set_property "steps.synth_design.args.no_srlextract" "0" $obj
set_property "steps.synth_design.args.shreg_min_size" "3" $obj
set_property "steps.synth_design.args.max_bram" "-1" $obj
set_property "steps.synth_design.args.max_uram" "-1" $obj
set_property "steps.synth_design.args.max_dsp" "-1" $obj
set_property "steps.synth_design.args.max_bram_cascade_height" "-1" $obj
set_property "steps.synth_design.args.max_uram_cascade_height" "-1" $obj
set_property "steps.synth_design.args.cascade_dsp" "auto" $obj
set_property "steps.synth_design.args.assert" "0" $obj
set_property -name {steps.synth_design.args.more options} -value {} -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k420tffg1156-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "constrset" "constrs_1" $obj
set_property "description" "Vivado Implementation Defaults" $obj
set_property "flow" "Vivado Implementation 2014" $obj
set_property "name" "impl_1" $obj
set_property "needs_refresh" "0" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "pr_configuration" "" $obj
set_property "srcset" "sources_1" $obj
set_property "strategy" "Vivado Implementation Defaults" $obj
set_property "incremental_checkpoint" "" $obj
set_property "include_in_archive" "1" $obj
set_property "steps.opt_design.is_enabled" "1" $obj
set_property "steps.opt_design.tcl.pre" "" $obj
set_property "steps.opt_design.tcl.post" "" $obj
set_property "steps.opt_design.args.verbose" "0" $obj
set_property "steps.opt_design.args.directive" "Default" $obj
set_property -name {steps.opt_design.args.more options} -value {} -objects $obj
set_property "steps.power_opt_design.is_enabled" "0" $obj
set_property "steps.power_opt_design.tcl.pre" "" $obj
set_property "steps.power_opt_design.tcl.post" "" $obj
set_property -name {steps.power_opt_design.args.more options} -value {} -objects $obj
set_property "steps.place_design.tcl.pre" "" $obj
set_property "steps.place_design.tcl.post" "" $obj
set_property "steps.place_design.args.directive" "Default" $obj
set_property -name {steps.place_design.args.more options} -value {} -objects $obj
set_property "steps.post_place_power_opt_design.is_enabled" "0" $obj
set_property "steps.post_place_power_opt_design.tcl.pre" "" $obj
set_property "steps.post_place_power_opt_design.tcl.post" "" $obj
set_property -name {steps.post_place_power_opt_design.args.more options} -value {} -objects $obj
set_property "steps.phys_opt_design.is_enabled" "0" $obj
set_property "steps.phys_opt_design.tcl.pre" "" $obj
set_property "steps.phys_opt_design.tcl.post" "" $obj
set_property "steps.phys_opt_design.args.directive" "Default" $obj
set_property -name {steps.phys_opt_design.args.more options} -value {} -objects $obj
set_property "steps.route_design.tcl.pre" "" $obj
set_property "steps.route_design.tcl.post" "" $obj
set_property "steps.route_design.args.directive" "Default" $obj
set_property -name {steps.route_design.args.more options} -value {} -objects $obj
set_property "steps.post_route_phys_opt_design.is_enabled" "0" $obj
set_property "steps.post_route_phys_opt_design.tcl.pre" "" $obj
set_property "steps.post_route_phys_opt_design.tcl.post" "" $obj
set_property "steps.post_route_phys_opt_design.args.directive" "Default" $obj
set_property -name {steps.post_route_phys_opt_design.args.more options} -value {} -objects $obj
set_property "steps.write_bitstream.tcl.pre" "" $obj
set_property "steps.write_bitstream.tcl.post" "" $obj
set_property "steps.write_bitstream.args.raw_bitfile" "0" $obj
set_property "steps.write_bitstream.args.mask_file" "0" $obj
set_property "steps.write_bitstream.args.no_binary_bitfile" "0" $obj
set_property "steps.write_bitstream.args.bin_file" "0" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.logic_location_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj
set_property -name {steps.write_bitstream.args.more options} -value {} -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:fpga_fc7_daq_firmware"
