#
# Vivado (TM) v2016.4 (64-bit)
#
# fpga_fc7_daq_firmware_create_vivado_project.tcl: Tcl script for re-creating project 'fpga_fc7_daq_firmware'
#
# Generated by Vivado on Sun Apr 02 22:56:05 +0200 2017
# IP Build 1755317 on Mon Jan 23 20:30:07 MST 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (fpga_fc7_daq_firmware_create_vivado_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_gt.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_tx_startup_fsm.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_rx_startup_fsm.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_recclk_monitor.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_sync_block.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_reset_sync.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_init.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_trans_decl.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_package.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/usr/user_package_basic.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/sys/system_package.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/gen_hdl/gig_eth_pcs_pma_v11_4/gig_eth_pcs_pma_v11_4_transceiver.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/icap/icap_package.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_tx_mux.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_txtransactor_if_simple.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_status_buffer.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxtransactor_if_simple.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_shim.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_mux.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rarp_block.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_packet_parser.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_ipaddr_block.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_tx.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_rx.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_do_rx_reset.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_clock_crossing_if.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_byte_sum.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_status.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_resend.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_ping.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_payload.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_arp.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_buffer_selector.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_sm.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_if.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_cfg.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/example_designs/hdl/clock_div.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/usr/user_addr_decode.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/sys/system_version_package.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/uc_spi_interface.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/uc_pipe_interface.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/trans_buffer.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_block.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipbus_addr_decode.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/hdl/emac_hostbus_decl.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/icap/icap_interface_ioControl.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/icap/icap_interface_fsm.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/icap/icap_interface.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/i2c/i2c_ctrl.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/i2c/i2c_bitwise.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_if_flat.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/trans_arb.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/stretcher.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/usr/user_version_package_basic.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/regs/system_regs.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/uc_if.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ip_mac_select.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipbus_sys_fabric.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ethernet/hdl/eth_7s_1000basex.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/clocks_7s_serdes_fc7.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/icap/icap_interface_wrapper.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/i2c/i2c_master_core.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/cdce/spi/spi_master.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_ctrl.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/sys/system_core.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/sys/fc7_top.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/sdpram_32x9_16x10.ngc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4.ngc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/tri_mode_eth_mac_v5_5.ngc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/sdpram_16x10_32x9.ngc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ipb_fc7/ipcore_dir/syspll.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/i2c/i2c_eep_autoread.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/i2c/i2c_master_top.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/usr/user_core.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/fast_command/fast_command_core.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/command_processor/command_processor_core.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/clock_generator/clock_generator_core.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/phy/phy_core.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ttc_dec/core/cpm_ttc_dec_wrapper.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ttc_dec/core/ttc_amc13_channels_a_b.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ttc_dec/core/iddr_amc13.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ttc_dec/ttc_decoder_block.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ttc_dec/core/TTC_decoder.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ttc_dec/core/TTC_hamming_decoder_alme.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/daqlink_7s_sync_block.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/daqlink_7s.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/FIFO_RESET_7S.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/TTS_TRIG_if.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/daqlink_7s_rx_startup_fsm.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/empty_evt/EmptyEvent.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/DAQ_LINK_Kintex.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/daqlink_7s_gt.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/daqlink_7s_tx_startup_fsm.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/EthernetCRCD32.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/RAM32x6Db.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/DAQ_Link_7S.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/daqlink_7s_init.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/Hamming.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_daq_link/crc16D16.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/amc13/amc13_block.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/be_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/cbc3/cbc3_trigdata_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/cbc3/cbc3_stubdata_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/cbc3/cbc3_data_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/data_buffer.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/cbc3/ip/cbc3_stubdata_shift/cbc3_stubdata_shift.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/evnt_cnt/evnt_cnt_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/test/internal_trigger_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ipbus_slaves/ipbus_decoder_cnfg.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ipbus_slaves/register_map_package.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ipbus_slaves/ipbus_decoder_stat.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ipbus_slaves/ipbus_decoder_ctrl.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/readout/fifo/readout_fifo_ctrl.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/readout/readout.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/tmp/user_pkg_cfg_modules.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/tmp/cbc3_data_sys_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/tmp/user_pkg_be_proc.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/tmp/data_packer.vhd"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ttc_dec/ip/ttc_dec_err_cnt/ttc_dec_err_cnt.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/clock_generator/ip/clock_gen_ip/mmcm/clock_gen_ip.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/clock_generator/ip/clock_ref_gen_ip/clock_ref_gen_ip.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/cbc3/ip/cbc3_stubdata_buf/cbc3_stubdata_buf.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/cbc3/ip/cbc3_trigdata_buf/cbc3_trigdata_buf.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/readout/fifo/ip/readout_fifo/readout_fifo.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/be_proc/evnt_cnt/ip/evnt_cnt_buf/evnt_cnt_buf.xci"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ucf/sys.xdc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ucf/usr_clk.xdc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ucf/user_io.xdc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ucf/usr_mgt_amc.xdc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/sys/ddr3_ls/constraints/ddr3_controller.xdc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ucf/usr_io_fmc.xdc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ucf/no_ddr3_controller.xdc"
#    "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/src/usr/ucf/usr_opt.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "fpga_fc7_daq_firmware_create_vivado_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/fpga_fc7_daq_firmware"]"

# Create project
create_project fpga_fc7_daq_firmware ./fpga_fc7_daq_firmware -part xc7k420tffg1156-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects fpga_fc7_daq_firmware]
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "read write" $obj
set_property "ip_output_repo" "C:/lcharles/cms/ph2/tkdaq/FC7TestBoard/v2016.4/FC7-Firmware/fw/prj/fpga_fc7_daq_firmware/fpga_fc7_daq_firmware/fpga_fc7_daq_firmware.cache/ip" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "sim.use_ip_compiled_libs" "0" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj
set_property "target_language" "VHDL" $obj
set_property "target_simulator" "ModelSim" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj
set_property "xsim.array_display_limit" "64" $obj
set_property "xsim.trace_limit" "65536" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_gt.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_tx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_rx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_recclk_monitor.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_sync_block.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_reset_sync.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_init.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_trans_decl.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_package.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_package_basic.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/system_package.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gig_eth_pcs_pma_v11_4/gig_eth_pcs_pma_v11_4_transceiver.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_package.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_tx_mux.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_txtransactor_if_simple.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_status_buffer.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxtransactor_if_simple.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_shim.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_mux.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rarp_block.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_packet_parser.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_ipaddr_block.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_tx.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_rx.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_do_rx_reset.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_clock_crossing_if.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_byte_sum.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_status.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_resend.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_ping.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_payload.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_arp.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_buffer_selector.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_sm.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_if.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_cfg.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/example_designs/hdl/clock_div.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_addr_decode.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/system_version_package.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/uc_spi_interface.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/uc_pipe_interface.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/trans_buffer.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_block.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipbus_addr_decode.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/emac_hostbus_decl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface_ioControl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_bitwise.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_if_flat.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/trans_arb.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/stretcher.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_version_package_basic.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/regs/system_regs.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/uc_if.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ip_mac_select.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipbus_sys_fabric.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/eth_7s_1000basex.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/clocks_7s_serdes_fc7.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/icap/icap_interface_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_master_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/cdce/spi/spi_master.vhd"]"\
 "[file normalize "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/system_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/sys/fc7_top.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_32x9_16x10.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/tri_mode_eth_mac_v5_5.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_16x10_32x9.ngc"]"\
 "[file normalize "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/syspll.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_eep_autoread.vhd"]"\
 "[file normalize "$origin_dir/../../src/sys/i2c/i2c_master_top.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/usr/user_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/fast_command/fast_command_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/command_processor/command_processor_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/clock_generator/clock_generator_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/phy/phy_core.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ttc_dec/core/cpm_ttc_dec_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ttc_dec/core/ttc_amc13_channels_a_b.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ttc_dec/core/iddr_amc13.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ttc_dec/ttc_decoder_block.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ttc_dec/core/TTC_decoder.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ttc_dec/core/TTC_hamming_decoder_alme.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_sync_block.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/FIFO_RESET_7S.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/TTS_TRIG_if.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_rx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/empty_evt/EmptyEvent.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/DAQ_LINK_Kintex.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_gt.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_tx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/EthernetCRCD32.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/RAM32x6Db.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/DAQ_Link_7S.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_init.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/Hamming.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_daq_link/crc16D16.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/amc13/amc13_block.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/be_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/cbc3/cbc3_trigdata_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/cbc3/cbc3_stubdata_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/cbc3/cbc3_data_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/data_buffer.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/cbc3/ip/cbc3_stubdata_shift/cbc3_stubdata_shift.xci"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/evnt_cnt/evnt_cnt_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/test/internal_trigger_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ipbus_slaves/ipbus_decoder_cnfg.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ipbus_slaves/register_map_package.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ipbus_slaves/ipbus_decoder_stat.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/ipbus_slaves/ipbus_decoder_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/readout/fifo/readout_fifo_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/readout/readout.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/tmp/user_pkg_cfg_modules.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/tmp/cbc3_data_sys_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/tmp/user_pkg_be_proc.vhd"]"\
 "[file normalize "$origin_dir/../../src/usr/be_proc/tmp/data_packer.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_gt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_tx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_rx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_recclk_monitor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_sync_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_reset_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gtwizard_v2_3_gbe/gtwizard_v2_3_gbe_init.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_trans_decl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/usr/user_package_basic.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/sys/system_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/gen_hdl/gig_eth_pcs_pma_v11_4/gig_eth_pcs_pma_v11_4_transceiver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_tx_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_txtransactor_if_simple.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_status_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxtransactor_if_simple.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_shim.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rxram_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_rarp_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_packet_parser.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_ipaddr_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram_rx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_dualportram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_do_rx_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_clock_crossing_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_byte_sum.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_status.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_resend.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_ping.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_payload.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_build_arp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_buffer_selector.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_sm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor_cfg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/example_designs/hdl/clock_div.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/usr/user_addr_decode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/sys/system_version_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/uc_spi_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/uc_pipe_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/trans_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4/example_design/gig_eth_pcs_pma_v11_4_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipbus_addr_decode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/emac_hostbus_decl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface_ioControl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_bitwise.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/udp_if_flat.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/trans_arb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/transactor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/stretcher.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/usr/user_version_package_basic.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/regs/system_regs.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/uc_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ip_mac_select.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipbus_sys_fabric.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ethernet/hdl/eth_7s_1000basex.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/clocks_7s_serdes_fc7.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/icap/icap_interface_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_master_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/cdce/spi/spi_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../ipbus_2_0_v1/firmware/ipbus_core/hdl/ipbus_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/sys/system_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/sys/fc7_top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_32x9_16x10.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/gig_eth_pcs_pma_v11_4.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/tri_mode_eth_mac_v5_5.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/sdpram_16x10_32x9.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/../../src/sys/ipb_fc7/ipcore_dir/syspll.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_eep_autoread.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/sys/i2c/i2c_master_top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/usr/user_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/fast_command/fast_command_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/command_processor/command_processor_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/clock_generator/clock_generator_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/phy/phy_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ttc_dec/core/cpm_ttc_dec_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ttc_dec/core/ttc_amc13_channels_a_b.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ttc_dec/core/iddr_amc13.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ttc_dec/ttc_decoder_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ttc_dec/core/TTC_decoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ttc_dec/core/TTC_hamming_decoder_alme.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_sync_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/FIFO_RESET_7S.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/TTS_TRIG_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_rx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/empty_evt/EmptyEvent.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/DAQ_LINK_Kintex.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_gt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_tx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/EthernetCRCD32.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/RAM32x6Db.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/DAQ_Link_7S.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/daqlink_7s_init.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/Hamming.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_daq_link/crc16D16.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/amc13/amc13_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/be_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/cbc3/cbc3_trigdata_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/cbc3/cbc3_stubdata_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/cbc3/cbc3_data_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/data_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/evnt_cnt/evnt_cnt_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/test/internal_trigger_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ipbus_slaves/ipbus_decoder_cnfg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ipbus_slaves/register_map_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ipbus_slaves/ipbus_decoder_stat.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/ipbus_slaves/ipbus_decoder_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/readout/fifo/readout_fifo_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/readout/readout.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/tmp/user_pkg_cfg_modules.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/tmp/cbc3_data_sys_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/tmp/user_pkg_be_proc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../src/usr/be_proc/tmp/data_packer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "fc7_top" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/usr/ttc_dec/ip/ttc_dec_err_cnt/ttc_dec_err_cnt.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/usr/clock_generator/ip/clock_gen_ip/mmcm/clock_gen_ip.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/usr/clock_generator/ip/clock_ref_gen_ip/clock_ref_gen_ip.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/usr/be_proc/cbc3/ip/cbc3_stubdata_buf/cbc3_stubdata_buf.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/usr/be_proc/cbc3/ip/cbc3_trigdata_buf/cbc3_trigdata_buf.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/usr/be_proc/readout/fifo/ip/readout_fifo/readout_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../src/usr/be_proc/evnt_cnt/ip/evnt_cnt_buf/evnt_cnt_buf.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/sys/ucf/sys.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/sys/ucf/sys.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "used_in" "implementation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/usr_clk.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/usr_clk.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "used_in" "implementation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/user_io.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/user_io.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "used_in" "implementation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/usr_mgt_amc.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/usr_mgt_amc.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/sys/ddr3_ls/constraints/ddr3_controller.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/sys/ddr3_ls/constraints/ddr3_controller.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/usr_io_fmc.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/usr_io_fmc.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/no_ddr3_controller.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/no_ddr3_controller.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../src/usr/ucf/usr_opt.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../src/usr/ucf/usr_opt.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "[file normalize "$origin_dir/../../src/sys/ucf/sys.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "modelsim.log_all_signals" "0" $obj
set_property "modelsim.use_explicit_decl" "1" $obj
set_property "modelsim.vhdl_syntax" "93" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k420tffg1156-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7k420tffg1156-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k420tffg1156-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:fpga_fc7_daq_firmware"
